repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-merge-conflict

  - repo: local
    hooks:
      - id: format-check
        name: format check
        entry: pnpm format:check
        language: system
        pass_filenames: false

      - id: lint
        name: lint
        entry: pnpm lint
        language: system
        pass_filenames: false

      - id: typecheck
        name: typecheck
        entry: pnpm typecheck
        language: system
        pass_filenames: false
