// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Framework = "react" | "nextjs" | "angular-ts" | "ember-ts" | "lit-ts" | "marko-ts" | "nuxt-ts" | "preact-ts" | "preact-ts-official" | "qwik-ts" | "react-ts" | "solid-ts" | "svelte-ts" | "vue-ts" | "vue";