// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface PreviewFile { path: string, language: string, content: string, truncated: boolean, }