// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Framework } from "./Framework";
import type { Linting } from "./Linting";
import type { Routing } from "./Routing";
import type { StateManagement } from "./StateManagement";
import type { Styling } from "./Styling";

export interface ProjectConfig { project_name: string, framework: Framework, styling: Styling, linting: Linting, state_management: StateManagement, routing: Routing, dependencies: Array<string>, dev_dependencies: Array<string>, }