// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type RecipeErrorCode = "invalid-recipe-id" | "invalid-option" | "incompatible-block-selection" | "invalid-custom-dependency" | "template-missing" | "generation-failed";