// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RecipeOption } from "./RecipeOption";
import type { RecipeVerification } from "./RecipeVerification";

export interface RecipeCatalogItem { id: string, name: string, description: string, tier: string, status: string, baseTemplate: string, options: Record<string, RecipeOption>, verification: RecipeVerification, }