// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CustomDependenciesPolicy } from "./CustomDependenciesPolicy";
import type { RecipeOption } from "./RecipeOption";
import type { RecipePreviewPolicy } from "./RecipePreviewPolicy";
import type { RecipeVerification } from "./RecipeVerification";

export interface RecipeManifest { id: string, name: string, description: string, tier: string, status: string, baseTemplate: string, blocks: Array<string>, options: Record<string, RecipeOption>, customDependencies: CustomDependenciesPolicy, verification: RecipeVerification, preview: RecipePreviewPolicy, }