// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PreviewFile } from "./PreviewFile";
import type { ProjectTreeNode } from "./ProjectTreeNode";
import type { RecipeVerification } from "./RecipeVerification";

export interface RecipePreviewDetailsResponse { recipeId: string, projectName: string, tree: ProjectTreeNode, curatedTree: ProjectTreeNode, selectedFiles: Array<PreviewFile>, files: Array<PreviewFile>, dependencies: Array<string>, devDependencies: Array<string>, commands: Array<string>, selectedBlocks: Array<string>, customDependencies: Array<string>, customDevDependencies: Array<string>, recipeTier: string, recipeStatus: string, supportStatus: string, baseTemplate: string, templateSnapshot: string, verification: RecipeVerification, warnings: Array<string>, }