// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface RecipeBlockManifest { id: string, name: string, description: string, category: string, status: string, filesTouched: Array<string>, }