// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RecipeOptionValue } from "./RecipeOptionValue";

export interface RecipeOption { label: string, description: string, default: string, values: Array<RecipeOptionValue>, }