// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RecipeErrorCode } from "./RecipeErrorCode";

export interface RecipeApiError { code: RecipeErrorCode, message: string, details: Record<string, string>, }