// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RecipeProjectExtras } from "./RecipeProjectExtras";

export interface RecipeProjectRequest { projectName: string, options: Record<string, string>, extras: RecipeProjectExtras, }