// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Routing = "app-router" | "pages-router" | "react-router" | "react-router-data" | "vue-router" | "none";