export default function HomeRoute() {
  return (
    <section className="space-y-6">
      <div className="space-y-3">
        <p className="text-sm font-medium uppercase tracking-wide text-slate-500">
          Generated by Scaffolder
        </p>
        <h1 className="max-w-2xl text-4xl font-bold tracking-tight text-slate-950">
          React Router App
        </h1>
        <p className="max-w-2xl text-lg leading-8 text-slate-600">
          Start from a Vite, React, TypeScript, Tailwind CSS, and React Router
          baseline that has already been wired together.
        </p>
      </div>
    </section>
  )
}
